export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const LOAD_ACCOUNT = 'LOAD_ACCOUNT';
export const SELECTED_ACCOUNT = 'SELECTED_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const LOAD_TRANSACTION = 'LOAD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

export const TRY_SIGNUP = 'TRY_SIGNUP';
export const TRY_LOGIN = 'TRY_LOGIN';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';