export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const LOAD_ACCOUNT = 'LOAD_ACCOUNT';
export const SELECTED_ACCOUNT = 'SELECTED_ACCOUNT';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const LOAD_TRANSACTION = 'LOAD_TRANSACTION';